export * from './deepserp/googleFlights.js'
export * from './deepserp/googleSearch.js'
export * from './deepserp/googleTrends.js'
export * from './deepserp/googleScholar.js'
export * from './universal/scrapeHtml.js'
export * from './universal/scrapeMarkdown.js'
export * from './universal/scrapeScreenshot.js'
